### ISSUE TITLE
Symlink warning

### ISSUE THREAD

**Issue by artemiialessandrini** [Danfoa/robotiq_2finger_grippers#3]
While controlling gripper using C++, catkin warning appears:
`Warning: Cannot symlink from /home/artemii/robotmove_ws/devel/.private/myworkcell_demo/lib/python2.7/dist-packages/robotiq_2f_gripper_control/__init__.py to existing file /home/artemii/robotmove_ws/devel/lib/python2.7/dist-packages/robotiq_2f_gripper_control/__init__.py
Warning: Source hash: fc022dd798d6b7e274f2ad0844eaeb0b
Warning: Dest hash: 0e8d2401a15010fceb3aab8bb23e71a5
`
Not sure, if it's related to the package. Thanks

**Comment by Danfoa** [comment]
I am not 100 % sure, but I will bet it is a problem with the catkin workspace build. 

Try cleaning your workspace by running `catkin clean`, if you are using catkin tools, or just remove the `log` `build` and `devel` folders of it.

Then, could you try to use both `catkin_make` and `catkin build` commands/tools to re-build the workspace, and to see if the warning arises again?
