### ISSUE TITLE
Self-collisions in gripper when used with MoveIt!

### ISSUE THREAD

**Issue by jeff-o** [Danfoa/robotiq_2finger_grippers#8]
Hello! I'm having trouble when using this package, using MoveIt to control a real robot. The 2-finger gripper is connected to a UR5 arm. All seems to be fine, with the gripper attached properly in rviz and moving as expected when commanded.

The trouble is with MoveIt. I used the MoveIt setup assistant to create a collision matrix, set up groups, etc. Yet when I launch MoveIt in rviz, the gripper seems to be colliding with itself. I get the following errors when MoveIt tries to plan:

- Found a contact between 'gripper_left_inner_knuckle' (type 'Robot link') and 'gripper_left_inner_finger' (type 'Robot link'), which constitutes a collision. Contact information is not stored.
- Collision checking is considered complete (collision was found and 0 contacts are stored)
- Start state appears to be in collision with respect to group manipulator

Can you suggest anything I might investigate to eliminate the collision condition I'm experiencing? Or a known reliable MoveIt! configuration? Thanks!

**Comment by Danfoa** [comment]
@jeff-o, The Robotiq gripper does not have in principle any risk of self-collision, as the only parts that collide are the fingertips and this behavior is expected. I would suggest you modify manually the collision matrix in the setup assistant to disable any gripper-links self collisions (i.e. gripper-links to gripper-links collisions). The autogenerated collision matrix often requires manual modifications in many robot architectures.  

Beware not to modify any self-collisions between your UR5 robot links and the gripper links, as these do in fact represent real self-collision risks.

**Comment by jeff-o** [comment]
Thanks for responding! It turns out the error was further up in my URDF. The error prevented collisions from being disabled, which manifested in the issue I was seeing with the gripper. 

Thanks again for creating this driver; having an action server and proper joint position is something that is sorely missing from the main branch!

**Comment by Danfoa** [comment]
@jeff-o Happy to hear it is useful.
