### ISSUE TITLE
Can I use this only in simulation?

### ISSUE THREAD

**Issue by davidrmdt** [Danfoa/robotiq_2finger_grippers#9]
I'm trying to use this package only in simulation, I don't have the real gripper. But I have an error that says:
    from pymodbus.client.sync import ModbusSerialClient
    ImportError: No module named pymodbus.client.sync
The question is, can I use this package without having the real gripper?

**Comment by Danfoa** [comment]
Sorry for the late response, yes you can. Simulation is one of the features of the package. 

The simulated gripper driver handles the fake operation of the gripper and the update of the `joint_state` variables accordingly:

https://github.com/Danfoa/robotiq_2finger_grippers/blob/42b0a40b2d8374fc8d6511b969ec98d1a8ea1b45/robotiq_2f_gripper_control/src/robotiq_2f_gripper_control/robotiq_2f_gripper_driver.py#L418-L542

Also, check the node `robotiq_2f_action_server` arguments, there you have a parameter called `sim`, which internally chooses to call the real driver controller or a simulated one.
